#!/usr/bin/env python3
"""Plot central density and stellar binary fraction versus time.

The input ``*.single`` and ``*.binary`` files are generated by
``petar.data.process``.  Central density uses the same six-neighbour local
density convention as PeTar's density-centre calculation, followed by the
density-weighted estimate sum(rho_i**2) / sum(rho_i).  Binary fraction is the
fraction of stars in binaries: 2*N_binary / (N_single + 2*N_binary).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial import cKDTree


def load_table(path: Path) -> np.ndarray:
    """Load a PeTar ASCII table, returning an empty 2-D array if it is empty."""
    if not path.exists():
        raise FileNotFoundError(f"Required file does not exist: {path}")
    if path.stat().st_size == 0:
        return np.empty((0, 0), dtype=float)
    data = np.loadtxt(path, ndmin=2)
    return np.asarray(data, dtype=float)


def load_stars(snapshot: Path) -> tuple[np.ndarray, np.ndarray, int, int]:
    """Return component masses/positions and single/binary system counts."""
    single = load_table(Path(f"{snapshot}.single"))
    binary = load_table(Path(f"{snapshot}.binary"))

    if single.size and single.shape[1] < 4:
        raise ValueError(f"{snapshot}.single has fewer than 4 columns")
    if binary.size and binary.shape[1] < 34:
        raise ValueError(
            f"{snapshot}.binary has fewer than 34 columns; "
            "this script expects PeTar ASCII binary output"
        )

    masses = []
    positions = []
    if single.size:
        masses.append(single[:, 0])
        positions.append(single[:, 1:4])
    if binary.size:
        # Binary layout: CM fields [0:10], then component 1 and component 2.
        masses.extend((binary[:, 10], binary[:, 30]))
        positions.extend((binary[:, 11:14], binary[:, 31:34]))

    if not masses:
        return np.empty(0), np.empty((0, 3)), 0, 0

    return (
        np.concatenate(masses),
        np.concatenate(positions, axis=0),
        single.shape[0] if single.size else 0,
        binary.shape[0] if binary.size else 0,
    )


def central_density(mass: np.ndarray, pos: np.ndarray) -> float:
    """Calculate the Casertano-Hut density-weighted central density."""
    n_star = mass.size
    if n_star < 7:
        return np.nan

    distance, index = cKDTree(pos).query(pos, k=7)
    # Match Core.calcDensityAndCenter in tools/analysis/lagrangian.py:
    # sum self plus the five closest neighbours inside the sixth-neighbour radius.
    neighbour_mass = mass[index[:, :-1]].sum(axis=1)
    r6 = distance[:, -1]
    valid = np.isfinite(r6) & (r6 > 0.0)
    if not np.any(valid):
        return np.nan

    rho = neighbour_mass[valid] / r6[valid] ** 3
    return float(np.sum(rho * rho) / np.sum(rho))


def read_snapshot_list(path: Path) -> list[Path]:
    base = path.parent
    snapshots = []
    for line in path.read_text().splitlines():
        name = line.strip()
        if name and not name.startswith("#"):
            item = Path(name)
            snapshots.append(item if item.is_absolute() else base / item)
    return snapshots


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot PeTar central density and 2Nb/Ntot against time."
    )
    parser.add_argument("--snap-list", default="data.snap.lst")
    parser.add_argument("--core", default="data.core")
    parser.add_argument("-o", "--output", default="core_density_binary_fraction.png")
    parser.add_argument(
        "--linear-density",
        action="store_true",
        help="Use a linear left y-axis instead of the default logarithmic scale.",
    )
    parser.add_argument(
        "--save-data",
        help="Optional output table with columns: time, central_density, binary_fraction, Nsingle, Nb, Ntot.",
    )
    parser.add_argument(
        "--binary-ymin",
        type=float,
        help="Lower limit of the binary-fraction axis (default: automatic).",
    )
    parser.add_argument(
        "--binary-ymax",
        type=float,
        help="Upper limit of the binary-fraction axis (default: automatic).",
    )
    args = parser.parse_args()

    snap_list = Path(args.snap_list)
    core = load_table(Path(args.core))
    snapshots = read_snapshot_list(snap_list)
    if core.shape[1] < 1:
        raise ValueError(f"{args.core} contains no time column")
    if len(snapshots) != core.shape[0]:
        raise ValueError(
            f"Snapshot count ({len(snapshots)}) does not match core rows "
            f"({core.shape[0]})"
        )

    density = np.empty(len(snapshots))
    fraction = np.empty(len(snapshots))
    counts = np.empty((len(snapshots), 3), dtype=int)
    for i, snapshot in enumerate(snapshots):
        mass, pos, n_single, n_binary = load_stars(snapshot)
        n_total = n_single + 2 * n_binary
        density[i] = central_density(mass, pos)
        fraction[i] = 2.0 * n_binary / n_total if n_total else np.nan
        counts[i] = n_single, n_binary, n_total

    time = core[:, 0]
    fig, left = plt.subplots(figsize=(8.0, 5.0), constrained_layout=True)
    right = left.twinx()

    density_line = left.plot(time, density, color="tab:blue", label="Central density")[0]
    fraction_line = right.plot(
        time, fraction, color="tab:red", label=r"Binary fraction $2N_b/N_{tot}$"
    )[0]
    left.set_xlabel("Time [Myr]")
    left.set_ylabel(r"Central density [$M_\odot\,\mathrm{pc}^{-3}$]", color="tab:blue")
    right.set_ylabel(r"Binary fraction $2N_b/N_{tot}$", color="tab:red")
    left.tick_params(axis="y", colors="tab:blue")
    right.tick_params(axis="y", colors="tab:red")
    if not args.linear_density:
        left.set_yscale("log")
    finite_fraction = fraction[np.isfinite(fraction)]
    if finite_fraction.size:
        fraction_min = float(finite_fraction.min())
        fraction_max = float(finite_fraction.max())
        fraction_span = fraction_max - fraction_min
        fraction_pad = max(0.1 * fraction_span, 0.01)
        binary_ymin = max(0.0, fraction_min - fraction_pad)
        binary_ymax = min(1.0, fraction_max + fraction_pad)
        if binary_ymax <= binary_ymin:
            binary_ymax = min(1.0, binary_ymin + 0.02)
    else:
        binary_ymin, binary_ymax = 0.0, 1.0
    if args.binary_ymin is not None:
        binary_ymin = args.binary_ymin
    if args.binary_ymax is not None:
        binary_ymax = args.binary_ymax
    if binary_ymax <= binary_ymin:
        raise ValueError("--binary-ymax must be greater than --binary-ymin")
    right.set_ylim(binary_ymin, binary_ymax)
    left.grid(alpha=0.25)
    left.legend(handles=[density_line, fraction_line], loc="best")

    fig.savefig(args.output, dpi=200)
    print(f"Saved figure: {args.output}")

    if args.save_data:
        table = np.column_stack((time, density, fraction, counts))
        np.savetxt(
            args.save_data,
            table,
            header="time central_density binary_fraction Nsingle Nb Ntot",
            fmt=["%.16e", "%.16e", "%.16e", "%d", "%d", "%d"],
        )
        print(f"Saved data: {args.save_data}")


if __name__ == "__main__":
    main()
